apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: ecr
      containers:
      - name: api
        image: 014440443810.dkr.ecr.us-east-2.amazonaws.com/fiap-restaurant:$imgTag
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        env:
          - name: ASPNETCORE_URLS
            value: http://*:5001
          - name: ConnectionStrings__ConnectionString
            value: $connectionString
          - name: Aws__PoolId
            value: $poolId
          - name: Aws__PoolClientId
            value: $poolClientId
        ports:
        - containerPort: 5001
          name: api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
---
apiVersion: v1
kind: Service
metadata:
  name: api-svs
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: api