name: Deploy to EKS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install kubectl
      uses: ianbelcher/eks-kubectl-action@master
      with:
        cluster_name: fiap-restaurant-g-cluster
        kubernetes_version: v1.21.0

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ vars.REGISTRY }}
        REPOSITORY: fiap-restaurant
        IMAGE_TAG: ${{ vars.IMAGE_TAG }}
      run: |
        docker build -t $REPOSITORY ./app/src
        docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --region us-east-2 --name fiap-restaurant-g-cluster

    - name: Get envs
      run: |
        echo "connectionString=${{ vars.CONNECTION_STRING }}" >> $GITHUB_ENV
        echo "poolId=${{ vars.POOL_ID }}" >> $GITHUB_ENV
        echo "poolClientId=${{ vars.POOL_CLIENT_ID }}" >> $GITHUB_ENV
        echo "imgTag=${{ vars.IMAGE_TAG }}" >> $GITHUB_ENV

    - name: Set envs
      run: |
        cd kubernets
        envsubst < api-gh.template.yml > api-gh.yml 
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f ./kubernets/api-gh.yml
